{% set name = "arm_pyart" %}
{% set version = "1.9.2" %}
{% set sha256 = "f1d3502242257a9306f2e06b1ca3aed5a6037b8a67066c58bc38a559d3ad3b8b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
    number: 1000

requirements:
    build:
        - python
        - numpy 1.11.*
        - trmm_rsl  # [not win]

    run:
        - python
        - numpy >=1.11
        - scipy
        - matplotlib
        - netcdf4
        - trmm_rsl  # [not win]

test:
    imports:
        - pyart

about:
    home: http://arm-doe.github.io/pyart/
    license: BSD-3-Clause
    summary: "Python ARM Radar Toolkit"

extra:
    recipe-maintainers:
        - jjhelmus
        - zssherman
