{% set name = "arm_pyart" %}
{% set version = "1.9.2" %}
{% set sha256 = "f1d3502242257a9306f2e06b1ca3aed5a6037b8a67066c58bc38a559d3ad3b8b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # Do not try to build the Fortran extension on Windows
    - 0001-disable-fortran-extension.patch  # [win]

build:
    number: 1000
    script:
      - export RSL_PATH=$PREFIX  # [not win]
      - "{{ PYTHON }} -m pip install . --no-deps -vvv"

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('fortran') }}  # [not win]
    host:
        - python
        - pip
        - numpy
        - trmm_rsl  # [not win]
    run:
        - python
        - {{ pin_compatible('numpy') }}
        - scipy
        - matplotlib
        - netcdf4
        - trmm_rsl  # [not win]

test:
    imports:
        - pyart

about:
    home: http://arm-doe.github.io/pyart/
    license: BSD-3-Clause
    summary: "Python ARM Radar Toolkit"

extra:
    recipe-maintainers:
        - jjhelmus
        - zssherman
