travis:
  secure:
    BINSTAR_TOKEN: M3/KxkR4BYLd87RP+g20G1ZUePvDRuctCvSNMiCqxmQg6NQTnY9yFYMRDB1Jj6WwdRlOK/eu9qwSkiva7zfeXbRpj+MmhQ4pcziS+Hw8hSt3bm2VCVkeD6GPY1ySc5d08SqfD/AIz3jYryc2mbSa0yoAm5rlBhWnPg4HH8Vimt35U2BV5bR3zFoxEPzGWLq1CXeDIGVlgVBG6LdSjerG4rp8om/SdyguXTQbYTgCP746bXkyJFIIoQ0gJFVvScZ88Jz7MYkUPsaGgxulQDRkbheNrv3OlCjue1NRvDwtVSofrICzgR/XaKcOk/G0p2BN8X22V2XLhvIb+u22Q6kLdQg4aHsZGvQQqcH9E7tPXNPZbu+JSwBEHRGnKlzhL5W+7HzK5V70zFPHxIBA54N/NK2bjMZ4Y4ASl5Keq3GkyJE7tzmN5N3kZpYQNZ++M0K1e94rsV12OF4OzPOp95LSA9idxnr1B0b+fT8fbZBYpf/D5OGn+STL2fcE4ouYUAg2N1zS5coF8c5aHWBobnXxmD7yJepJhL1mWPGvmKG9IpR5aRoZF83rL0AKU/szzwIEtmf5e04nso2CXNBDNgjdMjqiL+vxmvyfjzab5tY6HDGZNapCfaDZ+RQ3VSJXc9iULTaVHoXMhd4Kla66ANgbmkiOM6nakrUpxUwCSdxjDbc=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
